# Generated by Django 3.0.2 on 2020-01-09 03:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0002_soprtnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdb',
            name='pub_data',
            field=models.DateField(default=datetime.datetime(2020, 1, 9, 3, 47, 44, 641587, tzinfo=utc)),
        ),
    ]
