# Generated by Django 3.0.2 on 2020-01-09 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0004_auto_20200109_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdb',
            name='pub_data',
        ),
        migrations.AddField(
            model_name='newsdb',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 9, 4, 12, 17, 819889, tzinfo=utc)),
        ),
    ]
